### ISSUE TITLE
Is the project dead ?

### ISSUE THREAD

**Issue by vladpalos** [moai/moai-community#14]
Hi, 

Is this project dead ?

Thanks,
Vlad

**Comment by halfnelson** [comment]
Hi Vlad,

Most of the work has moved to the main moai/moai-dev repo for Moai 2.0. This will sit around to help people build v1.8.  MOAI 2.0 has a bunch of changes, the build scripts are in https://github.com/moai/moai-dev/tree/develop/cmake

All the best.
