### ISSUE TITLE
Ubuntu 16.04 build (and other linux probably) falis

### ISSUE THREAD

**Issue by iskolbin** [moai/moai-community#8]
Recently I tried to build (by pito) MOAI and build failed. After some digging in I found these problems:

1. SDL2 version is not updated (there is pull request fixing this https://github.com/moai/moai-community/pull/5)
```diff
diff --git a/cmake/third-party/sdl2/CMakeLists.txt b/cmake/third-party/sdl2/CMakeLists.txt
index b90f27f..c6b7c3f 100644
--- a/cmake/third-party/sdl2/CMakeLists.txt
+++ b/cmake/third-party/sdl2/CMakeLists.txt
@@ -15,7 +15,7 @@ include(CheckTypeSize)
 include(CheckStructHasMember)
 include(CMakeDependentOption)
 include(FindPkgConfig)
-set(SDL2_SOURCE_DIR "${MOAI_ROOT}/3rdparty/sdl2-2.0.0")
+set(SDL2_SOURCE_DIR "${MOAI_ROOT}/3rdparty/sdl2-2.0.4")
 set(CMAKE_MODULE_PATH "${SDL2_SOURCE_DIR}/cmake")
 include(${SDL2_SOURCE_DIR}/cmake/macros.cmake)
 include(${SDL2_SOURCE_DIR}/cmake/sdlchecks.cmake)
```
2. Incorrect paths to build scripts in bin/pito
```diff
diff --git a/bin/pito b/bin/pito
index a03f9a8..3b2d1f4 100755
--- a/bin/pito
+++ b/bin/pito
@@ -26,7 +26,7 @@ then
       
     ;;
     Linux*)
-        MOAI_BUILD_SCRIPT="bin/build-linux.sh"
+        MOAI_BUILD_SCRIPT="$PITO_HOME/scripts/build-linux.sh"
     ;;
     *)
         echo "Unknown OS"
```
3. Missing linker flags for SDL2 and dl
```diff
diff --git a/cmake/cmake-modules/platform-common.cmake b/cmake/cmake-modules/platform-common.cmake
index bc46344..d53da59 100644
--- a/cmake/cmake-modules/platform-common.cmake
+++ b/cmake/cmake-modules/platform-common.cmake
@@ -18,7 +18,7 @@ endif (LIB_PATH)
 
 set (CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${VFS_INCLUDE}")
 set (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${VFS_INCLUDE}")
-
+set (CMAKE_CXX_LINK_EXECUTABLE "${CMAKE_CXX_LINK_EXECUTABLE} -ldl -lSDL2")^M
 
 #
 # Set as debug
```
4. Lua Extensions is activated by default (MOAI_LUAEXT flag for cmake). I don't ever use this module and actually don't know it purpose. But it simply cannot be built for any Lua other than 5.1 because it uses defines which you cannot find neither in LuaJIT or in Lua 5.2 sources: LUAC_VERSION and LUAC_FORMAT. Another problem is that LuaJIT doesn't have lundump.h file. Also you need Instruction typedef. You can take all of them from Lua 5.1 sources and put in MOAI SDK sources src/moai-util/MOAILuaUtil.cpp:
```c
//#include <lundump.h>
#include <lua.h> // for LUA_SIGNATURE
#define LUAC_FORMAT 0x51
#define LUAC_VERSION 0
typedef int Instruction;
```
But I think it's much easier and safer just to disable Lua Extensions:
```diff
diff --git a/cmake/cmake-modules/module-config.cmake b/cmake/cmake-modules/module-config.cmake
index 39aa63f..097d65e 100644
--- a/cmake/cmake-modules/module-config.cmake
+++ b/cmake/cmake-modules/module-config.cmake
@@ -13,7 +13,7 @@ option ( MOAI_CRYPTO                  "Enable Moai Crypto classes"    TRUE )
 option ( MOAI_EXPAT                    "Enable Expat"                  TRUE )
 option ( MOAI_FREETYPE                 "Enable Freetype"               TRUE  )
 option ( MOAI_JSON                     "Enable Json"                   TRUE )
-option ( MOAI_LUAEXT                   "Enable Lua Extensions"         TRUE )
+option ( MOAI_LUAEXT                   "Enable Lua Extensions"         FALSE )
 option ( MOAI_MONGOOSE                 "Enable mongoose"               TRUE )
 option ( MOAI_OGG                      "Enable Ogg"                    TRUE )
 option ( MOAI_OPENSSL                  "Enable OpenSSL"                        TRUE )
```

After that build was successful. But I have enough doubts about my solution (3 and 4) so I post issue, not pull request. Hope you look in this, your're doing awesome job:)

**Comment by halfnelson** [comment]
thanks. I have updated the cmake scripts. I removed the custom cmakefile.txt for libsdl and used the one bundled in 3rdparty and disabled LUAJIT so that moai builds with lua5.1 by default (there are some good things in luaext that we don't want to drop), added to pull #9

**Comment by iskolbin** [comment]
Awesome! May I also ask about LUAEXT issue: I saw your changes in https://github.com/fallguyconsulting/moai-dev/commit/a87ff75f8ec0ae753ed2be02daf1efc49223d2d0 which I guess somehow solves problem with LuaJIT build, and this commit dated Oct 9, 2015. For me it's actually surprising that this changes is not included in current moai-dev branch. Well...I mean my brains just twisted how MOAI currently developed:)

**Comment by halfnelson** [comment]
That was in moai-util my guess is the change was lost when moving to
luaext.
